x-base: &base
  restart: unless-stopped
  logging:
    driver: json-file
    options:
      max-size: "12m"
      max-file: "5"
  networks:
    - isitrunning

networks:
  isitrunning:

services:
  soketi:
    <<: *base
    image: quay.io/soketi/soketi:latest-16-distroless
    ports:
      - "6001:6001"
      - "9601:9601"
    environment:
      - SOKETI_DEFAULT_APP_ENABLE_CLIENT_MESSAGES=true

  postgres:
    <<: *base
    image: postgres:18
    environment:
      - POSTGRES_DB=server
      - POSTGRES_USER=server
      - POSTGRES_PASSWORD=secret
    volumes:
      - ./.data/postgres:/var/lib/postgresql/18/docker
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U server -d server"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s

  pgbouncer:
    <<: *base
    image: edoburu/pgbouncer:v1.25.1-p0
    environment:
      - DATABASE_URL=postgres://server:secret@postgres/server
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -p 6432"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  server-ws:
    <<: *base
    build:
      context: src/server
      dockerfile: local.Dockerfile
      target: ws
    entrypoint: "/bin/bash"
    command: ["-c", "while true; do sleep 3000; done;"]
    volumes:
      - ./src/server:/opt/server
    working_dir: /opt/server
    depends_on:
      pgbouncer:
        condition: service_healthy
